; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

@g = global [6 x i64] zeroinitializer, align 16

define ptr @freeze_gep_inbounds_global() {
; CHECK-LABEL: @freeze_gep_inbounds_global(
; CHECK-NEXT:    ret ptr getelementptr inbounds nuw (i8, ptr @g, i64 8)
;
  %fr = freeze ptr getelementptr inbounds (i8, ptr @g, i64 8)
  ret ptr %fr
}

define ptr @freeze_gep_inbounds_alloca() {
; CHECK-LABEL: @freeze_gep_inbounds_alloca(
; CHECK-NEXT:    [[A:%.*]] = alloca [32 x i8], align 1
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw i8, ptr [[A]], i64 16
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %a = alloca [32 x i8], align 1
  %gep = getelementptr inbounds i8, ptr %a, i64 16
  %fr = freeze ptr %gep
  ret ptr %fr
}

define ptr @freeze_gep_inbounds_global_boundary() {
; CHECK-LABEL: @freeze_gep_inbounds_global_boundary(
; CHECK-NEXT:    ret ptr getelementptr inbounds nuw (i8, ptr @g, i64 48)
;
  %fr = freeze ptr getelementptr inbounds (i8, ptr @g, i64 48)
  ret ptr %fr
}

define ptr @freeze_gep_inbounds_global_oob() {
; CHECK-LABEL: @freeze_gep_inbounds_global_oob(
; CHECK-NEXT:    [[FR:%.*]] = freeze ptr getelementptr inbounds nuw (i8, ptr @g, i64 49)
; CHECK-NEXT:    ret ptr [[FR]]
;
  %fr = freeze ptr getelementptr inbounds (i8, ptr @g, i64 49)
  ret ptr %fr
}

define ptr @freeze_gep_inbounds_global_negative() {
; CHECK-LABEL: @freeze_gep_inbounds_global_negative(
; CHECK-NEXT:    [[FR:%.*]] = freeze ptr getelementptr inbounds (i8, ptr @g, i64 -1)
; CHECK-NEXT:    ret ptr [[FR]]
;
  %fr = freeze ptr getelementptr inbounds (i8, ptr @g, i64 -1)
  ret ptr %fr
}

define ptr @freeze_gep_inbounds_alloca_variable_offset(i64 %n) {
; CHECK-LABEL: @freeze_gep_inbounds_alloca_variable_offset(
; CHECK-NEXT:    [[A:%.*]] = alloca [32 x i8], align 1
; CHECK-NEXT:    [[N_FR:%.*]] = freeze i64 [[N:%.*]]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i8, ptr [[A]], i64 [[N_FR]]
; CHECK-NEXT:    ret ptr [[GEP]]
;
  %a = alloca [32 x i8], align 1
  %gep = getelementptr inbounds i8, ptr %a, i64 %n
  %fr = freeze ptr %gep
  ret ptr %fr
}
